defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "**/*.html"
    values:
      layout: "blank"
  -
    scope:
      path: "projects"
    values:
      layout: "default"
      type: "project"
  

collections:
  reports:

kramdown:
  math_engine: null

titles_from_headings:
  enabled: false
