defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

collections:
  reports:

kramdown:
  math_engine: null

titles_from_headings:
  enabled: false
